# This is the centralised config for all jobs that need an npm cache
# Currently this is
# - build frontend
.npm-cache-config:
  cache:
    key: "mlreef-node-cache"
    paths:
      - /usr/local/lib/node_modules
      - web/node_modules


build gateway:
  # import the centralised caching configuration for npm caches
  extends: [".base-docker-build", ".npm-cache-config"]
  only:
    changes:
      # changes on specific bin scripts
      - web/bin/ci-build-frontend
      # all files and folders under web/src and web/public
      - web/public/**/*
      - web/src/**/*
      # all files in the web directory
      - web/*
  # This docker version should correspond with the on docker version in the EC2 deployment
  script: |
    docker build --tag "$GATEWAY_IMAGE_PATH" -f web/Dockerfile web  \
      --build-arg CI_COMMIT_REF_SLUG="$CI_COMMIT_REF_SLUG"          \
      --build-arg CI_PIPELINE_ID="$CI_PIPELINE_ID"
    docker push "$GATEWAY_IMAGE_PATH"
    if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
      GATEWAY_LATEST_IMAGE_PATH=$(echo $GATEWAY_IMAGE_PATH | sed 's/:\(.*\)$/:latest/')
      docker tag $GATEWAY_IMAGE_PATH $GATEWAY_LATEST_IMAGE_PATH
      docker push $GATEWAY_LATEST_IMAGE_PATH
    fi
